[build]
publish = "public"
command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.41"

[[redirects]]
  from = "https://formosaagora.netlify.com/*"
  to = "https://novo.formosaagora.com.br/:splat 301!"
